providers: 
    tigros: 
        isEnabled: true
        username: gino.pilotino@gmail.com
        password: MySuperSecretPassword
    esselunga:
        isEnabled: true
        username: gino.pilotino@gmail.com
        password: MySuperSecretPassword
slack: 
    isEnabled: true
    webhook: https://hooks.slack.com/services/[my-slack-channel-webook]

misc:
    minutesInterval: 10